<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SimioAPI">
      <HintPath>C:\Program Files\Simio LLC\Simio\SimioAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
